#!/bin/bash
# FAST Layout Switcher for Punto

# UID and ADDRESS are usually constant for a session
# We take them from the environment or fast lookup
USER_ID=${USER_ID:-1000}
USER_NAME=${USER_NAME:-anton}
DBUS_ADDR="unix:path=/run/user/$USER_ID/bus"

# 1. Get current index FAST (no grep/awk if possible)
CUR=$(sudo -u "$USER_NAME" DBUS_SESSION_BUS_ADDRESS="$DBUS_ADDR" gsettings get org.gnome.desktop.input-sources current)
# CUR is "uint32 X"
[[ "$CUR" == *"0"* ]] && NEXT=1 || NEXT=0
[[ "$NEXT" == "1" ]] && ENG="xkb:ru::rus" || ENG="xkb:us::eng"

# 2. Switch (IBus is faster for input, gsettings for HUD)
sudo -u "$USER_NAME" DBUS_SESSION_BUS_ADDRESS="$DBUS_ADDR" ibus engine "$ENG" &
sudo -u "$USER_NAME" DBUS_SESSION_BUS_ADDRESS="$DBUS_ADDR" gsettings set org.gnome.desktop.input-sources current "$NEXT" &

# We run them in background (&) to return to Punto IMMEDIATELY
wait
